# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 851)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMaximumSize(QtCore.QSize(230, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gBoxHist_toolbar = QtWidgets.QGroupBox(self.frame)
        self.gBoxHist_toolbar.setCheckable(True)
        self.gBoxHist_toolbar.setObjectName("gBoxHist_toolbar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gBoxHist_toolbar)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkBoxHist_ShowHint = QtWidgets.QCheckBox(self.gBoxHist_toolbar)
        self.chkBoxHist_ShowHint.setChecked(True)
        self.chkBoxHist_ShowHint.setObjectName("chkBoxHist_ShowHint")
        self.verticalLayout.addWidget(self.chkBoxHist_ShowHint)
        self.verticalLayout_2.addWidget(self.gBoxHist_toolbar)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 9, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 11, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 12, 0, 1, 1)
        self.btnHist_tightLayout = QtWidgets.QPushButton(self.groupBox_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/39.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHist_tightLayout.setIcon(icon)
        self.btnHist_tightLayout.setObjectName("btnHist_tightLayout")
        self.gridLayout.addWidget(self.btnHist_tightLayout, 1, 0, 1, 2)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 12, 1, 1, 1)
        self.chkBoxHist_Legend = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkBoxHist_Legend.setChecked(True)
        self.chkBoxHist_Legend.setObjectName("chkBoxHist_Legend")
        self.gridLayout.addWidget(self.chkBoxHist_Legend, 2, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_9.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_9.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_9.addWidget(self.radioButton_5)
        self.gridLayout.addWidget(self.groupBox_3, 3, 0, 1, 2)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 11, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 9, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 121))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setMinimumSize(QtCore.QSize(0, 41))
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_7.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setMinimumSize(QtCore.QSize(0, 41))
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_7.addWidget(self.radioButton_2)
        self.gridLayout.addWidget(self.groupBox, 5, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_2, 0, QtCore.Qt.AlignTop)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pushButton_27 = QtWidgets.QPushButton(self.frame)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_2.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.frame)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_2.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(self.frame)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_2.addWidget(self.pushButton_29)
        self.pushButton_30 = QtWidgets.QPushButton(self.frame)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_2.addWidget(self.pushButton_30)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame)
        self.widgetHist = QmyFigureCanvas(self.frame_2)
        self.widgetHist.setObjectName("widgetHist")
        self.horizontalLayout.addWidget(self.widgetHist)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gBoxHist_toolbar_2 = QtWidgets.QGroupBox(self.frame_10)
        self.gBoxHist_toolbar_2.setCheckable(True)
        self.gBoxHist_toolbar_2.setObjectName("gBoxHist_toolbar_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gBoxHist_toolbar_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chkBoxHist_ShowHint_2 = QtWidgets.QCheckBox(self.gBoxHist_toolbar_2)
        self.chkBoxHist_ShowHint_2.setChecked(True)
        self.chkBoxHist_ShowHint_2.setObjectName("chkBoxHist_ShowHint_2")
        self.verticalLayout_4.addWidget(self.chkBoxHist_ShowHint_2)
        self.verticalLayout_14.addWidget(self.gBoxHist_toolbar_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_10)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_13.setSpacing(12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btnHist_tightLayout_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.btnHist_tightLayout_2.setIcon(icon)
        self.btnHist_tightLayout_2.setObjectName("btnHist_tightLayout_2")
        self.verticalLayout_13.addWidget(self.btnHist_tightLayout_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_5.setMinimumSize(QtCore.QSize(119, 118))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_10.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_10.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_10.addWidget(self.radioButton_8)
        self.verticalLayout_13.addWidget(self.groupBox_5)
        self.verticalLayout_14.addWidget(self.groupBox_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_14.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_14.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_14.addWidget(self.pushButton_10)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_14.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_14.addWidget(self.pushButton_11)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_14.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_14.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_14.addWidget(self.pushButton_15)
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_14.addWidget(self.pushButton_25)
        self.pushButton_31 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_31.setObjectName("pushButton_31")
        self.verticalLayout_14.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_32.setObjectName("pushButton_32")
        self.verticalLayout_14.addWidget(self.pushButton_32)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frame_10)
        self.widgetFill = QmyFigureCanvas(self.frame_3)
        self.widgetFill.setObjectName("widgetFill")
        self.horizontalLayout_2.addWidget(self.widgetFill)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gBoxHist_toolbar_3 = QtWidgets.QGroupBox(self.frame_7)
        self.gBoxHist_toolbar_3.setCheckable(True)
        self.gBoxHist_toolbar_3.setObjectName("gBoxHist_toolbar_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gBoxHist_toolbar_3)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.chkBoxHist_ShowHint_3 = QtWidgets.QCheckBox(self.gBoxHist_toolbar_3)
        self.chkBoxHist_ShowHint_3.setChecked(True)
        self.chkBoxHist_ShowHint_3.setObjectName("chkBoxHist_ShowHint_3")
        self.verticalLayout_6.addWidget(self.chkBoxHist_ShowHint_3)
        self.verticalLayout_5.addWidget(self.gBoxHist_toolbar_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_7)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnPie_tightLayout = QtWidgets.QPushButton(self.groupBox_4)
        self.btnPie_tightLayout.setIcon(icon)
        self.btnPie_tightLayout.setObjectName("btnPie_tightLayout")
        self.gridLayout_3.addWidget(self.btnPie_tightLayout, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_7)
        self.groupBox_7.setMinimumSize(QtCore.QSize(119, 118))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_12.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_12.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_12.addWidget(self.radioButton_11)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_5.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_5.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_5.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_5.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_5.addWidget(self.pushButton_20)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_5.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_5.addWidget(self.pushButton_23)
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_5.addWidget(self.pushButton_21)
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_5.addWidget(self.pushButton_26)
        self.pushButton_33 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_33.setObjectName("pushButton_33")
        self.verticalLayout_5.addWidget(self.pushButton_33)
        self.pushButton_34 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_34.setObjectName("pushButton_34")
        self.verticalLayout_5.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_35.setObjectName("pushButton_35")
        self.verticalLayout_5.addWidget(self.pushButton_35)
        self.pushButton_36 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_36.setObjectName("pushButton_36")
        self.verticalLayout_5.addWidget(self.pushButton_36)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_7.addWidget(self.frame_7)
        self.widgetPie = QmyFigureCanvas(self.frame_4)
        self.widgetPie.setObjectName("widgetPie")
        self.horizontalLayout_7.addWidget(self.widgetPie)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/exit_24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon1)
        self.actQuit.setObjectName("actQuit")
        self.actTightLayout = QtWidgets.QAction(MainWindow)
        self.actTightLayout.setIcon(icon)
        self.actTightLayout.setObjectName("actTightLayout")
        self.actScatterAgain = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/017.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actScatterAgain.setIcon(icon2)
        self.actScatterAgain.setObjectName("actScatterAgain")
        self.actSetCursor = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/range.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSetCursor.setIcon(icon3)
        self.actSetCursor.setObjectName("actSetCursor")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "机器学习算法系统"))
        self.gBoxHist_toolbar.setTitle(_translate("MainWindow", "导航工具栏"))
        self.chkBoxHist_ShowHint.setText(_translate("MainWindow", "显示坐标提示"))
        self.groupBox_2.setTitle(_translate("MainWindow", "图表操作"))
        self.pushButton_6.setText(_translate("MainWindow", "GBDT"))
        self.pushButton_5.setText(_translate("MainWindow", "AdaBoost"))
        self.pushButton_2.setText(_translate("MainWindow", "贝叶斯"))
        self.pushButton_4.setText(_translate("MainWindow", "BP"))
        self.btnHist_tightLayout.setText(_translate("MainWindow", "紧凑布局"))
        self.pushButton_24.setText(_translate("MainWindow", "Logistic"))
        self.chkBoxHist_Legend.setText(_translate("MainWindow", "显示图例"))
        self.pushButton.setText(_translate("MainWindow", "k-近邻"))
        self.groupBox_3.setTitle(_translate("MainWindow", "数据集选择"))
        self.radioButton_3.setText(_translate("MainWindow", "大数据集"))
        self.radioButton_4.setText(_translate("MainWindow", "中数据集"))
        self.radioButton_5.setText(_translate("MainWindow", "小数据集"))
        self.pushButton_7.setText(_translate("MainWindow", "随机森林"))
        self.pushButton_3.setText(_translate("MainWindow", "决策树"))
        self.groupBox.setTitle(_translate("MainWindow", "choice"))
        self.radioButton.setText(_translate("MainWindow", "ROC"))
        self.radioButton_2.setText(_translate("MainWindow", "SCATTER"))
        self.label.setText(_translate("MainWindow", "评价指标"))
        self.pushButton_27.setText(_translate("MainWindow", "accuracy"))
        self.pushButton_28.setText(_translate("MainWindow", "precision_weighted"))
        self.pushButton_29.setText(_translate("MainWindow", "recall_weighted"))
        self.pushButton_30.setText(_translate("MainWindow", "f1_weighted"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "分类"))
        self.gBoxHist_toolbar_2.setTitle(_translate("MainWindow", "导航工具栏"))
        self.chkBoxHist_ShowHint_2.setText(_translate("MainWindow", "显示坐标提示"))
        self.groupBox_6.setTitle(_translate("MainWindow", "图表操作"))
        self.btnHist_tightLayout_2.setText(_translate("MainWindow", "紧凑布局"))
        self.groupBox_5.setTitle(_translate("MainWindow", "数据集选择"))
        self.radioButton_6.setText(_translate("MainWindow", "大数据集"))
        self.radioButton_7.setText(_translate("MainWindow", "中数据集"))
        self.radioButton_8.setText(_translate("MainWindow", "小数据集"))
        self.pushButton_8.setText(_translate("MainWindow", "贝叶斯网络"))
        self.pushButton_9.setText(_translate("MainWindow", "马尔科夫模型"))
        self.pushButton_10.setText(_translate("MainWindow", "线性回归"))
        self.pushButton_12.setText(_translate("MainWindow", "岭回归"))
        self.pushButton_11.setText(_translate("MainWindow", "XGBoost"))
        self.pushButton_13.setText(_translate("MainWindow", "多项式回归"))
        self.pushButton_14.setText(_translate("MainWindow", "决策树回归"))
        self.pushButton_15.setText(_translate("MainWindow", "平均绝对误差"))
        self.pushButton_25.setText(_translate("MainWindow", "均方误差"))
        self.pushButton_31.setText(_translate("MainWindow", "中值绝对误差"))
        self.pushButton_32.setText(_translate("MainWindow", "R2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "预测"))
        self.gBoxHist_toolbar_3.setTitle(_translate("MainWindow", "导航工具栏"))
        self.chkBoxHist_ShowHint_3.setText(_translate("MainWindow", "显示坐标提示"))
        self.groupBox_4.setTitle(_translate("MainWindow", "图表操作"))
        self.btnPie_tightLayout.setText(_translate("MainWindow", "紧凑布局"))
        self.groupBox_7.setTitle(_translate("MainWindow", "数据集选择"))
        self.radioButton_9.setText(_translate("MainWindow", "大数据集"))
        self.radioButton_10.setText(_translate("MainWindow", "中数据集"))
        self.radioButton_11.setText(_translate("MainWindow", "小数据集"))
        self.pushButton_16.setText(_translate("MainWindow", "K-means"))
        self.pushButton_17.setText(_translate("MainWindow", "BIRCH"))
        self.pushButton_18.setText(_translate("MainWindow", "DBSACN"))
        self.pushButton_19.setText(_translate("MainWindow", "GMM"))
        self.pushButton_20.setText(_translate("MainWindow", "OPTICS"))
        self.pushButton_22.setText(_translate("MainWindow", "CLIQUE"))
        self.pushButton_23.setText(_translate("MainWindow", "MeanShift"))
        self.pushButton_21.setText(_translate("MainWindow", "兰德系数"))
        self.pushButton_26.setText(_translate("MainWindow", "互信息"))
        self.pushButton_33.setText(_translate("MainWindow", "同质性"))
        self.pushButton_34.setText(_translate("MainWindow", "轮廓系数"))
        self.pushButton_35.setText(_translate("MainWindow", "Calinski_Harabasz"))
        self.pushButton_36.setText(_translate("MainWindow", "Dbi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "聚类"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出"))
        self.actTightLayout.setText(_translate("MainWindow", "紧凑布局"))
        self.actTightLayout.setToolTip(_translate("MainWindow", "重新紧凑布局"))
        self.actScatterAgain.setText(_translate("MainWindow", "重新生成散点数据"))
        self.actScatterAgain.setToolTip(_translate("MainWindow", "重新生成散点数据"))
        self.actSetCursor.setText(_translate("MainWindow", "十字光标"))
        self.actSetCursor.setToolTip(_translate("MainWindow", "设置为十字光标"))

from myFigureCanvas import QmyFigureCanvas
import res_rc
